name: build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            compiler: clang++
          - os: ubuntu-latest
            compiler: clang++
          - os: macos-latest
            compiler: clang++
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5
      - name: Configure
        shell: bash
        run: cmake -S . -B build -G Ninja -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DLEONMUSIC_ENABLE_TAGLIB=OFF
      - name: Build
        shell: bash
        run: cmake --build build --config Release
